name: Build VCV Rack Plugin
on: [push, pull_request, workflow_dispatch]

env:
  rack-sdk-version: 2.6.6

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:        
        - {
            name: Linux,
            os: ubuntu-latest,
            build_shell: "bash",
            prepare-os: sudo apt-get -y --allow-downgrades --allow-remove-essential --allow-change-held-packages update,
            prepare-os2: sudo apt install -y libglu-dev,
            postfix: lin-x64
          }
        - {
            name: MacOS-Intel,
            os: macos-latest,
            build_shell: "bash",
            prepare-os: "",
            prepare-os2: "",
            postfix: mac-x64
          }          
        - {
            name: MacOS-ARM,
            os: macos-latest,
            build_shell: "bash",
            prepare-os: "",
            prepare-os2: "",
            postfix: mac-arm64
          }
        - {
            name: Windows,
            os: windows-latest,
            build_shell: "msys2 {0}",
            prepare-os: export CC=gcc,
            prepare-os2: "",
            postfix: win-x64
          }
        language: [ 'cpp' ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
            msystem: MINGW64
            update: true
            install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-tools unzip zip

      - name: Get Rack-SDK
        shell: ${{ matrix.config.build_shell }}
        run: |
          curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-${{ matrix.config.postfix }}.zip
          unzip Rack-SDK.zip
      - name: Patch plugin.mk, use 7zip on Windows
        if: runner.os == 'Windows'
        run: |
          sed -i 's/zip -q -9 -r/7z a -tzip -mx=9/' $HOME/Rack-SDK/plugin.mk
      - name: Modify plugin version
        # only modify plugin version if no tag was created
        if: "! startsWith(github.ref, 'refs/tags/v')"
        run: |
          gitrev=`git rev-parse --short HEAD`
          pluginversion=`jq -r '.version' plugin.json`
          echo "Set plugin version from $pluginversion to $pluginversion-$gitrev"
          cat <<< `jq --arg VERSION "$pluginversion" '.version=$VERSION' plugin.json` > plugin.json
      - name: Initialize CodeQL
        if: runner.os == 'Linux'
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - name: Build plugin
        shell: ${{ matrix.config.build_shell }}
        run: |
          ${{ matrix.config.prepare-os }}
          ${{ matrix.config.prepare-os2 }}
          export RACK_DIR=$(pwd)/Rack-SDK
          make -j dep
          make -j dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: ${{ matrix.config.name }}
      - name: Perform CodeQL Analysis
        if: runner.os == 'Linux'
        uses: github/codeql-action/analyze@v4

  publish:
    name: Publish plugin
    # only create a release if a tag was created that is called e.g. v1.2.3
    # see also https://vcvrack.com/manual/Manifest#version
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Check if plugin version matches tag
        run: |
          pluginversion=`jq -r '.version' plugin.json`
          if [ "v$pluginversion" != "${{ env.GITHUB_REF_NAME }}" ]; then
            echo "Plugin version from plugin.json 'v$pluginversion' doesn't match with tag version '${{ env.GITHUB_REF_NAME }}'"
            exit 1
          fi
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ env.GITHUB_REPOSITORY_NAME }} VCV Rack Plugin ${{ env.GITHUB_REF_NAME }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v4
        with:
          path: _artifacts
          pattern: '*'
          merge-multiple: true
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _artifacts/**/*.vcvplugin
          tag: ${{ github.ref }}
          file_glob: true
