name: Build MetaModule Plugin

on: [workflow_dispatch]

jobs:
  build-arm:
    name: Build for MetaModule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: plugin

      # Checkout the 4ms SDK
      - name: Checkout MetaModule SDK
        uses: actions/checkout@v4
        with:
          repository: 4ms/metamodule-plugin-sdk
          path: metamodule-plugin-sdk
          submodules: recursive

      # Install compilation tools and Inkscape
      - name: Install ARM toolchain and Inkscape
        run: |
          sudo apt-get update
          # install Inkscape
          sudo apt-get install -y cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi inkscape

      # Convert SVGs to PNGs
      - name: Convert Assets (SVG -> PNG)
        run: |
          # 4ms script
          python3 metamodule-plugin-sdk/scripts/SvgToPng.py --input plugin/res/ComponentLibrary --output plugin/res/ComponentLibrary
          python3 metamodule-plugin-sdk/scripts/SvgToPng.py --input plugin/res --output plugin/res

      # Build using CMake
      - name: Configure and Build
        run: |
          cd plugin
          # pass the SDK path, which triggers the metamodule condition in CMakelists
          cmake -B build -G Ninja -DMETAMODULE_SDK_DIR=$GITHUB_WORKSPACE/metamodule-plugin-sdk
          cmake --build build

      # Upload result
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MetaModule-Plugin
          path: plugin/build/*.mmplugin
          retention-days: 2

  publish-mm:
    name: Add to Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # see all tags

      - name: Get Release Tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # find the latest tag
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "Detected latest tag: $LATEST_TAG"
            echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT
          else
            # If triggered by tag, use that tag
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - uses: actions/download-artifact@v4
        with:
          name: MetaModule-Plugin
          path: _artifacts

      - name: Upload to Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          # with no name or body here, it adds the file to existing release
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          files: _artifacts/*.mmplugin